/*
 * SPDX-FileCopyrightText: 2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef _SOC_CPU_MATRIX_AXI_IC_REG_H_
#define _SOC_CPU_MATRIX_AXI_IC_REG_H_


#ifdef __cplusplus
extern "C" {
#endif
#include "soc.h"

#define CPU_MATRIX_AXI_IC_AXI_IC_DATE_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x0)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DATE : R/W ;bitpos:[31:0] ;default: 32'd23050900 ; */
/*description: Version Control Register.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DATE    0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DATE_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_DATE_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_DATE_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DATE_V  0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DATE_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_CLK_EN_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x4)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_CLK_EN : R/W ;bitpos:[0] ;default: 1'd0 ; */
/*description: value 1 enable clk, value 0 disable clk, default 1.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_CLK_EN    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_CLK_EN_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_CLK_EN_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_CLK_EN_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_INTERRUPT_RAW_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x8)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_RAW : R/SS/WTC ;bitpos:[1] ;default: 1'd0 ; */
/*description: Interrupt raw of reg_timeout_int_raw.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_RAW    (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_RAW_M  (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_RAW_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_RAW_S  1
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_RAW : R/SS/WTC ;bitpos:[0] ;default: 1'd0 ; */
/*description: Interrupt raw of reg_dec_failure_int_raw.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_RAW    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_RAW_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_RAW_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_RAW_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_INTERRUPT_CLR_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xC)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_CLR : WT ;bitpos:[1] ;default: 1'd0 ; */
/*description: Interrupt clr of reg_timeout_int_clr.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_CLR    (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_CLR_M  (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_CLR_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_CLR_S  1
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_CLR : WT ;bitpos:[0] ;default: 1'd0 ; */
/*description: Interrupt clr of reg_dec_failure_int_clr.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_CLR    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_CLR_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_CLR_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_CLR_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_INTERRUPT_ENA_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x10)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ENA : R/W ;bitpos:[1] ;default: 1'd0 ; */
/*description: Interrupt ena of reg_timeout_int_ena.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ENA    (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ENA_M  (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ENA_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ENA_S  1
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ENA : R/W ;bitpos:[0] ;default: 1'd0 ; */
/*description: Interrupt ena of reg_dec_failure_int_ena.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ENA    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ENA_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ENA_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ENA_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_INTERRUPT_ST_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x14)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ST : RO ;bitpos:[1] ;default: 1'd0 ; */
/*description: Interrupt st of reg_timeout_int_st.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ST    (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ST_M  (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ST_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_INT_ST_S  1
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ST : RO ;bitpos:[0] ;default: 1'd0 ; */
/*description: Interrupt st of reg_dec_failure_int_st.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ST    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ST_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ST_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_INT_ST_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_TIMEOUT_MAX_CNT_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x18)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_MAX_CNT : R/W ;bitpos:[31:0] ;default: 32'd4294967295 ; */
/*description: AXI IC core AW or AR channel timeout counter maximum value..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_MAX_CNT    0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_MAX_CNT_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_MAX_CNT_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_MAX_CNT_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_MAX_CNT_V  0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_MAX_CNT_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_TIMEOUT_INFO_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x1C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_WR : RO ;bitpos:[13] ;default: 1'd0 ; */
/*description: 1 indicates write operation, 0 indicates read operation..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_WR    (BIT(13))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_WR_M  (BIT(13))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_WR_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_WR_S  13
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_ID : RO ;bitpos:[12:4] ;default: 9'd0 ; */
/*description: (master id, awid).*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_ID    0x000001FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_ID_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_ID_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_ID_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_ID_V  0x1FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_ID_S  4
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_SLAVE : RO ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: bit[i] is 1 means slave[i] occurs timeout..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_SLAVE    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_SLAVE_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_SLAVE_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_SLAVE_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_SLAVE_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_TIMEOUT_SLAVE_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_DEC_FAILURE_INFO_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x20)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_MST_ID : RO ;bitpos:[14:6] ;default: 9'd0 ; */
/*description: (master id, awid/arid).*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_MST_ID    0x000001FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_MST_ID_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_MST_ID_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_MST_ID_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_MST_ID_V  0x1FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_MST_ID_S  6
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_CAUSE : RO ;bitpos:[5:3] ;default: 3'd0 ; */
/*description: bit[0] is 0 means to access the mapped slave address, and is 1 means to access t
he unmapped slave address. bit[1] is 0 means to access the visiable slave, and i
s 1 means to access the invisible slave. bit[2] is 0 means to access the secure
slave, and is 1 means to access the non-secure slave..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_CAUSE    0x00000007
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_CAUSE_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_CAUSE_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_CAUSE_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_CAUSE_V  0x7
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_CAUSE_S  3
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_TYPE : RO ;bitpos:[2] ;default: 1'd0 ; */
/*description: Decoder failure type control. 0 means ar failure, 1 means aw failure..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_TYPE    (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_TYPE_M  (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_TYPE_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_TYPE_S  2
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_VALID : RO ;bitpos:[1] ;default: 1'd0 ; */
/*description: Decoder failure valid control..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_VALID    (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_VALID_M  (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_VALID_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_VALID_S  1
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_READ_FIRST : R/W ;bitpos:[0] ;default: 1'd0 ; */
/*description: Decoder failure recorded control. 1 means record read failure first, else write
failure first..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_READ_FIRST    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_READ_FIRST_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_READ_FIRST_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_READ_FIRST_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_QOS_DEBUG_MST_SEL_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x24)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_QOS_DEBUG_MST_SEL : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: select which master whill be debug..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_QOS_DEBUG_MST_SEL    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_QOS_DEBUG_MST_SEL_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_QOS_DEBUG_MST_SEL_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_QOS_DEBUG_MST_SEL_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_QOS_DEBUG_MST_SEL_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_QOS_DEBUG_MST_SEL_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_PEAK_RATE_MODE_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x28)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_MODE : R/W ;bitpos:[0] ;default: 8'b0 ; */
/*description: peak rate, to control the aw channel request token num more than 1, default 0..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_MODE    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_MODE_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_MODE_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_MODE_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_PEAK_RATE_MODE_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x2C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_MODE : R/W ;bitpos:[0] ;default: 8'b0 ; */
/*description: peak rate, to control the ar channel request token num  more than 1, default 0..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_MODE    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_MODE_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_MODE_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_MODE_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_DEC_FAILURE_ADDR_L_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x80)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_L : RO ;bitpos:[31:0] ;default: 32'd0 ; */
/*description: AXI IC core AW or AR channel decoder failure address..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_L    0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_L_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_L_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_L_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_L_V  0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_L_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_DEC_FAILURE_ADDR_H_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x84)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_H : RO ;bitpos:[7:0] ;default: 8'd0 ; */
/*description: AXI IC core AW or AR channel decoder failure address..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_H    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_H_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_H_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_H_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_H_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_DEC_FAILURE_ADDR_H_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x88)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_3 : R/W ;bitpos:[3] ;default: 1'd0 ; */
/*description: 1 means safe and 0 means not safe..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_3    (BIT(3))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_3_M  (BIT(3))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_3_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_3_S  3
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_2 : R/W ;bitpos:[2] ;default: 1'd0 ; */
/*description: 1 means safe and 0 means not safe..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_2    (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_2_M  (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_2_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_2_S  2
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_1 : R/W ;bitpos:[1] ;default: 1'd0 ; */
/*description: 1 means safe and 0 means not safe..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_1    (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_1_M  (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_1_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_1_S  1
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_0 : R/W ;bitpos:[0] ;default: 1'd0 ; */
/*description: 1 means safe and 0 means not safe..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_0    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_0_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_0_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_IS_SECURE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_SLAVE_SECURITY_OVERRIDE_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x8C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_3 : R/W ;bitpos:[3] ;default: 1'd0 ; */
/*description: 0 means not overridden, and 1 means overridden..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_3    (BIT(3))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_3_M  (BIT(3))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_3_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_3_S  3
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_2 : R/W ;bitpos:[2] ;default: 1'd0 ; */
/*description: 0 means not overridden, and 1 means overridden..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_2    (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_2_M  (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_2_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_2_S  2
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_1 : R/W ;bitpos:[1] ;default: 1'd0 ; */
/*description: 0 means not overridden, and 1 means overridden..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_1    (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_1_M  (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_1_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_1_S  1
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_0 : R/W ;bitpos:[0] ;default: 1'd0 ; */
/*description: 0 means not overridden, and 1 means overridden..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_0    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_0_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_0_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_SLAVE_SECURITY_OVERRIDE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MASTER_IS_SECURE_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x90)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_IS_SECURE_0 : R/W ;bitpos:[0] ;default: 1'd0 ; */
/*description: 1 means safe and 0 means not safe..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_IS_SECURE_0    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_IS_SECURE_0_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_IS_SECURE_0_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_IS_SECURE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MASTER_SECURITY_OVERRIDE_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x94)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_SECURITY_OVERRIDE_0 : R/W ;bitpos:[0] ;default: 1'd0 ; */
/*description: 0 means not overridden, and 1 means overridden..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_SECURITY_OVERRIDE_0    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_SECURITY_OVERRIDE_0_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_SECURITY_OVERRIDE_0_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MASTER_SECURITY_OVERRIDE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_VALUE_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x98)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_VALUE_0 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core AW QOS value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_VALUE_0    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_VALUE_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_VALUE_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_VALUE_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_VALUE_0_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_VALUE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_VALUE_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x9C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_VALUE_0 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core AR QOS value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_VALUE_0    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_VALUE_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_VALUE_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_VALUE_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_VALUE_0_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_VALUE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_B_PRIOR_VALUE_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xA0)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_0 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core B priority value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_0    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_0_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_B_PRIOR_VALUE_1_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xA4)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_1 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core B priority value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_1    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_1_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_1_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_1_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_1_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_1_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_B_PRIOR_VALUE_2_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xA8)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_2 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core B priority value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_2    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_2_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_2_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_2_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_2_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_2_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_B_PRIOR_VALUE_3_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xAC)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_3 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core B priority value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_3    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_3_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_3_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_3_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_3_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_B_PRIOR_VALUE_3_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_R_PRIOR_VALUE_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xB0)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_0 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core R priority value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_0    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_0_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_R_PRIOR_VALUE_1_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xB4)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_1 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core R priority value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_1    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_1_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_1_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_1_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_1_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_1_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_R_PRIOR_VALUE_2_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xB8)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_2 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core R priority value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_2    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_2_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_2_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_2_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_2_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_2_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_R_PRIOR_VALUE_3_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xBC)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_3 : R/W ;bitpos:[3:0] ;default: 4'd0 ; */
/*description: AXI IC core R priority value specified by software..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_3    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_3_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_3_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_3_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_3_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_R_PRIOR_VALUE_3_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_SEL_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xC0)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_SEL_0 : R/W ;bitpos:[1:0] ;default: 2'd0 ; */
/*description: 2'b00 selects the original QOS value, 2'b01 selects the QOS value set by the sof
tware, 2'b10 selects the QOS value set by the QOS regulator..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_SEL_0    0x00000003
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_SEL_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_SEL_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_SEL_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_SEL_0_V  0x3
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_SEL_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_SEL_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xC4)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_SEL_0 : R/W ;bitpos:[1:0] ;default: 2'd0 ; */
/*description: 2'b00 selects the original QOS value, 2'b01 selects the QOS value set by the sof
tware, 2'b10 selects the QOS value set by the QOS regulator..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_SEL_0    0x00000003
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_SEL_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_SEL_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_SEL_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_SEL_0_V  0x3
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_SEL_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_RECOVERY_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xC8)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_3 : R/W ;bitpos:[3] ;default: 1'd0 ; */
/*description: Use QOS_COPY in SI_IF AW payload when it is asserted, otherwise use QOS_NEW (fro
m QOS regulator or software)..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_3    (BIT(3))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_3_M  (BIT(3))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_3_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_3_S  3
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_2 : R/W ;bitpos:[2] ;default: 1'd0 ; */
/*description: Use QOS_COPY in SI_IF AW payload when it is asserted, otherwise use QOS_NEW (fro
m QOS regulator or software)..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_2    (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_2_M  (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_2_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_2_S  2
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_1 : R/W ;bitpos:[1] ;default: 1'd0 ; */
/*description: Use QOS_COPY in SI_IF AW payload when it is asserted, otherwise use QOS_NEW (fro
m QOS regulator or software)..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_1    (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_1_M  (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_1_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_1_S  1
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_0 : R/W ;bitpos:[0] ;default: 1'd0 ; */
/*description: Use QOS_COPY in SI_IF AW payload when it is asserted, otherwise use QOS_NEW (fro
m QOS regulator or software)..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_0    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_0_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_0_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_RECOVERY_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_RECOVERY_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xCC)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_3 : R/W ;bitpos:[3] ;default: 1'd0 ; */
/*description: Use QOS_COPY in SI_IF AR payload when it is asserted, otherwise use QOS_NEW (fro
m QOS regulator or software)..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_3    (BIT(3))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_3_M  (BIT(3))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_3_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_3_S  3
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_2 : R/W ;bitpos:[2] ;default: 1'd0 ; */
/*description: Use QOS_COPY in SI_IF AR payload when it is asserted, otherwise use QOS_NEW (fro
m QOS regulator or software)..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_2    (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_2_M  (BIT(2))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_2_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_2_S  2
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_1 : R/W ;bitpos:[1] ;default: 1'd0 ; */
/*description: Use QOS_COPY in SI_IF AR payload when it is asserted, otherwise use QOS_NEW (fro
m QOS regulator or software)..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_1    (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_1_M  (BIT(1))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_1_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_1_S  1
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_0 : R/W ;bitpos:[0] ;default: 1'd0 ; */
/*description: Use QOS_COPY in SI_IF AR payload when it is asserted, otherwise use QOS_NEW (fro
m QOS regulator or software)..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_0    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_0_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_0_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_RECOVERY_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_ID_MASK_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xD0)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_MASK_0 : R/W ;bitpos:[7:0] ;default: 8'd15 ; */
/*description: mask for enable qos of aw channel id..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_MASK_0    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_MASK_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_MASK_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_MASK_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_MASK_0_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_MASK_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_ID_MASK_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xD4)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_MASK_0 : R/W ;bitpos:[7:0] ;default: 8'd15 ; */
/*description: mask for enable qos of ar channel id..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_MASK_0    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_MASK_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_MASK_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_MASK_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_MASK_0_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_MASK_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_ID_FILTER_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xD8)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_FILTER_0 : R/W ;bitpos:[7:0] ;default: 8'd15 ; */
/*description: filter for enable qos of aw channel id..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_FILTER_0    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_FILTER_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_FILTER_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_FILTER_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_FILTER_0_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ID_FILTER_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_ID_FILTER_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xDC)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_FILTER_0 : R/W ;bitpos:[7:0] ;default: 8'd15 ; */
/*description: filter for enable qos of ar channel id..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_FILTER_0    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_FILTER_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_FILTER_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_FILTER_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_FILTER_0_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ID_FILTER_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_CTRL_CFG_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xE0)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CTRL_CFG_0 : R/W ;bitpos:[31:0] ;default: 32'd8208 ; */
/*description: bit[0] enable channel qos, bit[1] enable debug, bit[7:4] mode of vlu regulate, b
it[15:8] step of dly thr, bit[16] dly cnt rst..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CTRL_CFG_0    0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CTRL_CFG_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CTRL_CFG_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CTRL_CFG_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CTRL_CFG_0_V  0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CTRL_CFG_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_CTRL_CFG_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xE4)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CTRL_CFG_0 : R/W ;bitpos:[31:0] ;default: 32'd8208 ; */
/*description: bit[0] enable channel qos, bit[1] enable debug, bit[7:4] mode of vlu regulate, b
it[15:8] step of dly thr, bit[16] dly cnt rst..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CTRL_CFG_0    0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CTRL_CFG_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CTRL_CFG_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CTRL_CFG_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CTRL_CFG_0_V  0xFFFFFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CTRL_CFG_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_TRANS_RATE_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xE8)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_TRANS_RATE_0 : R/W ;bitpos:[15:0] ;default: 16'd12296 ; */
/*description: transaction rate, to control the aw channel bandwidth, default 8 cycles 3 tokens
..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_TRANS_RATE_0    0x0000FFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_TRANS_RATE_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_TRANS_RATE_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_TRANS_RATE_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_TRANS_RATE_0_V  0xFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_TRANS_RATE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_TRANS_RATE_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xEC)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_TRANS_RATE_0 : R/W ;bitpos:[15:0] ;default: 16'd12296 ; */
/*description: transaction rate, to control the ar channel bandwidth, default 8 cycles 3 tokens
..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_TRANS_RATE_0    0x0000FFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_TRANS_RATE_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_TRANS_RATE_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_TRANS_RATE_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_TRANS_RATE_0_V  0xFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_TRANS_RATE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_PEAK_RATE_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xF0)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_0 : R/W ;bitpos:[7:0] ;default: 8'd0 ; */
/*description: peak rate, to control the aw channel request issue rate, default 0..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_0    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_0_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_PEAK_RATE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_PEAK_RATE_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xF4)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_0 : R/W ;bitpos:[7:0] ;default: 8'd0 ; */
/*description: peak rate, to control the ar channel request issue rate, default 0..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_0    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_0_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_PEAK_RATE_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_BURSTINESS_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xF8)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BURSTINESS_0 : R/W ;bitpos:[11:0] ;default: 12'd128 ; */
/*description: the maximum numbers of the aw channel token, default 128 tokens..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BURSTINESS_0    0x00000FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BURSTINESS_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BURSTINESS_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BURSTINESS_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BURSTINESS_0_V  0xFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BURSTINESS_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_BURSTINESS_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0xFC)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BURSTINESS_0 : R/W ;bitpos:[11:0] ;default: 12'd128 ; */
/*description: the maximum numbers of the ar channel token, default 128 tokens..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BURSTINESS_0    0x00000FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BURSTINESS_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BURSTINESS_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BURSTINESS_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BURSTINESS_0_V  0xFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BURSTINESS_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_CFG_VLU_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x100)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CFG_VLU_0 : R/W ;bitpos:[15:0] ;default: 16'd55906 ; */
/*description: the four level of the aw channel qos priority, default is 2,6,10,13.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CFG_VLU_0    0x0000FFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CFG_VLU_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CFG_VLU_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CFG_VLU_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CFG_VLU_0_V  0xFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_CFG_VLU_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_CFG_VLU_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x104)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CFG_VLU_0 : R/W ;bitpos:[15:0] ;default: 16'd55906 ; */
/*description: the four level of the ar channel qos priority, default is 2,6,10,13.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CFG_VLU_0    0x0000FFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CFG_VLU_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CFG_VLU_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CFG_VLU_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CFG_VLU_0_V  0xFFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_CFG_VLU_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_DLY_THR0_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x108)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR0_0 : R/W ;bitpos:[12:0] ;default: 13'd32 ; */
/*description: the first level of the aw channel delay threshold, default is 32..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR0_0    0x00001FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR0_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR0_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR0_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR0_0_V  0x1FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR0_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_DLY_THR1_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x10C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR1_0 : R/W ;bitpos:[12:0] ;default: 13'd160 ; */
/*description: the second level of the aw channel delay threshold, default is 160..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR1_0    0x00001FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR1_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR1_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR1_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR1_0_V  0x1FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR1_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_DLY_THR2_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x110)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR2_0 : R/W ;bitpos:[12:0] ;default: 13'd416 ; */
/*description: the third level of the aw channel delay threshold, default is 416..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR2_0    0x00001FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR2_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR2_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR2_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR2_0_V  0x1FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR2_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_DLY_THR3_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x114)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR3_0 : R/W ;bitpos:[12:0] ;default: 13'd928 ; */
/*description: the forth level of the aw channel delay threshold, default is 928..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR3_0    0x00001FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR3_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR3_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR3_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR3_0_V  0x1FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DLY_THR3_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_DLY_THR0_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x118)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR0_0 : R/W ;bitpos:[12:0] ;default: 13'd32 ; */
/*description: the first level of the ar channel delay threshold, default is 32..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR0_0    0x00001FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR0_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR0_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR0_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR0_0_V  0x1FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR0_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_DLY_THR1_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x11C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR1_0 : R/W ;bitpos:[12:0] ;default: 13'd160 ; */
/*description: the second level of the ar channel delay threshold, default is 160..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR1_0    0x00001FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR1_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR1_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR1_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR1_0_V  0x1FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR1_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_DLY_THR2_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x120)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR2_0 : R/W ;bitpos:[12:0] ;default: 13'd416 ; */
/*description: the third level of the ar channel delay threshold, default is 416..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR2_0    0x00001FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR2_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR2_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR2_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR2_0_V  0x1FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR2_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_DLY_THR3_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x124)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR3_0 : R/W ;bitpos:[12:0] ;default: 13'd928 ; */
/*description: the forth level of the ar channel delay threshold, default is 928..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR3_0    0x00001FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR3_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR3_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR3_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR3_0_V  0x1FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DLY_THR3_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_BUR_LEN_THR_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x128)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BUR_LEN_THR_0 : R/W ;bitpos:[9:0] ;default: 10'd64 ; */
/*description: limit the starting token value of aw channel to turn on transmission, default va
lue is 64, 0 means no limit..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BUR_LEN_THR_0    0x000003FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BUR_LEN_THR_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BUR_LEN_THR_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BUR_LEN_THR_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BUR_LEN_THR_0_V  0x3FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BUR_LEN_THR_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_BUR_LEN_THR_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x12C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BUR_LEN_THR_0 : R/W ;bitpos:[9:0] ;default: 10'd64 ; */
/*description: limit the starting token value of ar channel to turn on transmission, default va
lue is 64, 0 menas no limit..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BUR_LEN_THR_0    0x000003FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BUR_LEN_THR_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BUR_LEN_THR_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BUR_LEN_THR_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BUR_LEN_THR_0_V  0x3FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BUR_LEN_THR_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_DBG_TK_THR_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x130)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DBG_TK_THR_0 : R/W ;bitpos:[7:0] ;default: 8'd16 ; */
/*description: limit the debug sample interval, default value is 16.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DBG_TK_THR_0    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DBG_TK_THR_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DBG_TK_THR_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DBG_TK_THR_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DBG_TK_THR_0_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_DBG_TK_THR_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_DBG_TK_THR_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x134)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DBG_TK_THR_0 : R/W ;bitpos:[7:0] ;default: 8'd16 ; */
/*description: limit the debug sample interval, default value is 16.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DBG_TK_THR_0    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DBG_TK_THR_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DBG_TK_THR_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DBG_TK_THR_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DBG_TK_THR_0_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_DBG_TK_THR_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MAX_OST_AW_S_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x138)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_0 : R/W ;bitpos:[5:0] ;default: 6'd15 ; */
/*description: limit the number of outstanding for slave port, default value is 15, max is 32..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_0    0x0000003F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_0_V  0x3F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MAX_OST_AW_S_1_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x13C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_1 : R/W ;bitpos:[5:0] ;default: 6'd15 ; */
/*description: limit the number of outstanding for slave port, default value is 15, max is 32..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_1    0x0000003F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_1_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_1_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_1_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_1_V  0x3F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_1_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MAX_OST_AW_S_2_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x140)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_2 : R/W ;bitpos:[5:0] ;default: 6'd15 ; */
/*description: limit the number of outstanding for slave port, default value is 15, max is 32..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_2    0x0000003F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_2_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_2_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_2_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_2_V  0x3F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_2_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MAX_OST_AW_S_3_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x144)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_3 : R/W ;bitpos:[5:0] ;default: 6'd15 ; */
/*description: limit the number of outstanding for slave port, default value is 15, max is 32..*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_3    0x0000003F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_3_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_3_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_3_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_3_V  0x3F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AW_S_3_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MAX_OST_AR_S_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x148)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_0 : R/W ;bitpos:[7:0] ;default: 8'd15 ; */
/*description: limit the number of outstanding for slave port, default value is 15.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_0    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_0_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MAX_OST_AR_S_1_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x14C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_1 : R/W ;bitpos:[7:0] ;default: 8'd15 ; */
/*description: limit the number of outstanding for slave port, default value is 15.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_1    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_1_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_1_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_1_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_1_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_1_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MAX_OST_AR_S_2_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x150)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_2 : R/W ;bitpos:[7:0] ;default: 8'd15 ; */
/*description: limit the number of outstanding for slave port, default value is 15.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_2    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_2_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_2_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_2_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_2_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_2_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_MAX_OST_AR_S_3_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x154)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_3 : R/W ;bitpos:[7:0] ;default: 8'd15 ; */
/*description: limit the number of outstanding for slave port, default value is 15.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_3    0x000000FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_3_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_3_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_3_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_3_V  0xFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_MAX_OST_AR_S_3_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_BANDW_AUTO_ADJ_EN_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x158)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_EN_0 : R/W ;bitpos:[0] ;default: 1'b0 ; */
/*description: enable the qos bandwidth auto adjust function.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_EN_0    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_EN_0_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_EN_0_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_EN_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_BANDW_AUTO_ADJ_EN_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x15C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_EN_0 : R/W ;bitpos:[0] ;default: 1'b0 ; */
/*description: enable the qos bandwidth auto adjust function.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_EN_0    (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_EN_0_M  (BIT(0))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_EN_0_V  0x1
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_EN_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_BANDW_AUTO_ADJ_STEP_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x160)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_STEP_0 : R/W ;bitpos:[3:0] ;default: 4'd4 ; */
/*description: the step for qos auto adjust to adjust the transrate cycle.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_STEP_0    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_STEP_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_STEP_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_STEP_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_STEP_0_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_BANDW_AUTO_ADJ_STEP_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_BANDW_AUTO_ADJ_STEP_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x164)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_STEP_0 : R/W ;bitpos:[3:0] ;default: 4'd4 ; */
/*description: the step for qos auto adjust to adjust the transrate cycle.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_STEP_0    0x0000000F
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_STEP_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_STEP_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_STEP_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_STEP_0_V  0xF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_BANDW_AUTO_ADJ_STEP_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_ADJ_TOKEN_OVER_LIMIT_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x168)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_OVER_LIMIT_0 : R/W ;bitpos:[11:0] ;default: 12'd192 ; */
/*description: when token num more than this limit and remain a limit time, will auto adjust tr
ansrate.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_OVER_LIMIT_0    0x00000FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_OVER_LIMIT_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_OVER_LIMIT_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_OVER_LIMIT_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_OVER_LIMIT_0_V  0xFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_OVER_LIMIT_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_ADJ_TOKEN_OVER_LIMIT_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x16C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_OVER_LIMIT_0 : R/W ;bitpos:[11:0] ;default: 12'd192 ; */
/*description: when token num more than this limit and remain a limit time, will auto adjust tr
ansrate.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_OVER_LIMIT_0    0x00000FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_OVER_LIMIT_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_OVER_LIMIT_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_OVER_LIMIT_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_OVER_LIMIT_0_V  0xFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_OVER_LIMIT_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_ADJ_TOKEN_UNDER_LIMIT_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x170)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_UNDER_LIMIT_0 : R/W ;bitpos:[11:0] ;default: 12'd16 ; */
/*description: when token num less than this limit and remain a limit time, will auto adjust tr
ansrate.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_UNDER_LIMIT_0    0x00000FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_UNDER_LIMIT_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_UNDER_LIMIT_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_UNDER_LIMIT_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_UNDER_LIMIT_0_V  0xFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TOKEN_UNDER_LIMIT_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_ADJ_TOKEN_UNDER_LIMIT_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x174)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_UNDER_LIMIT_0 : R/W ;bitpos:[11:0] ;default: 12'd16 ; */
/*description: when token num less than this limit and remain a limit time, will auto adjust tr
ansrate.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_UNDER_LIMIT_0    0x00000FFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_UNDER_LIMIT_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_UNDER_LIMIT_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_UNDER_LIMIT_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_UNDER_LIMIT_0_V  0xFFF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TOKEN_UNDER_LIMIT_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AW_QOS_ADJ_TIME_LIMIT_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x178)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TIME_LIMIT_0 : R/W ;bitpos:[9:0] ;default: 10'd16 ; */
/*description: when token num less or more than token limit and remain this limit time, will au
to adjust transrate.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TIME_LIMIT_0    0x000003FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TIME_LIMIT_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TIME_LIMIT_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TIME_LIMIT_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TIME_LIMIT_0_V  0x3FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AW_QOS_ADJ_TIME_LIMIT_0_S  0

#define CPU_MATRIX_AXI_IC_AXI_IC_AR_QOS_ADJ_TIME_LIMIT_0_REG          (DR_REG_CPU_MATRIX_AXI_IC_BASE + 0x17C)
/* CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TIME_LIMIT_0 : R/W ;bitpos:[9:0] ;default: 10'd16 ; */
/*description: when token num less or more than token limit and remain this limit time, will au
to adjust transrate.*/
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TIME_LIMIT_0    0x000003FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TIME_LIMIT_0_M  ((CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TIME_LIMIT_0_V)<<(CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TIME_LIMIT_0_S))
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TIME_LIMIT_0_V  0x3FF
#define CPU_MATRIX_AXI_IC_AXI_IC_REG_AR_QOS_ADJ_TIME_LIMIT_0_S  0


#ifdef __cplusplus
}
#endif



#endif /*_SOC_CPU_MATRIX_AXI_IC_REG_H_ */
